### ISSUE TITLE
A better error message please

### ISSUE THREAD

**Issue by agentlewis** [Shopify/node-themekit#25] opened 2018-08-31 17:45 UTC
### Problem
I am getting a simple error message when using node-themekit (where as I wasn't with vanilla themekit) :)

However it would be far more helpful if it told me what file it was erroring in. Even more helpful would be the line number.

![screenshot at 2018-08-31 19-40-30](https://user-images.githubusercontent.com/1431991/44927701-c0024600-ad55-11e8-8898-295e65ae62b9.png)

Would this be something to do with themekit or node-themekit? my hunch is themekit right?

However it is strange that I get the error report in node-themekit but not themekit :confused:

**Comment by erickzhao** [comment] 2018-09-01 05:50
Very interesting issue! I investigated a bit, and it seems like your problem has two parts to it.

## Path not showing in node-themekit error
You're right - adding the path in would be on Theme Kit's side. It seems like `0.8.0` added a more descriptive error message (shows you what went wrong instead of giving you a `422` error code), but removed the asset path from the error message. By downgrading the required version in `lib/config.js` to `0.7.5`, I was able to get an error message with the asset path:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/16010076/44942725-d1b01180-ad86-11e8-9faf-187d40ce82ed.png">

However, it seems like there has been a change to add this back at the next release (see [this commit](https://github.com/Shopify/themekit/commit/2fb6ae705ab54e64ff58d5f5233944518e07777f)). This should be fixed soon!

## Errors not showing in Theme Kit
The error is actually there - this seems to be an issue with how ThemeKit is handling STDIO.

### What happens in the Theme Kit executable
If you run `theme deploy` on Theme Kit `0.8.0`, it briefly flashes any error before erasing itself to show the complete deploy message. This will both not show the error, and give a weird duplication of the progress bar.

![screencast 2018-09-01 01-21-13](https://user-images.githubusercontent.com/16010076/44942677-8e08d800-ad85-11e8-915a-98299eb61cc9.gif)

This can be reproducible - the more errors you get, the more duplicated progress bars appear in the console.

### Why it still shows in node-themekit
`node-themekit` runs Theme Kit in as a child process. However, in [lib/run-executable.js](https://github.com/Shopify/node-themekit/blob/master/lib/run-executable.js), we're overwriting the default STDIO from Theme Kit with custom behaviour, namely:

```javascript
//  accumulate any errors
childProcess.stderr.on('data', (data) => {
    errors += data;
});

...

childProcess.on('close', () => {
    // ensure promise is rejected with errors
    if (errors) {
       reject(errors);
    }

    ...
});
```

If we wanted to replicate Theme Kit's output, we could remove all the aforementioned custom STDIO and add `stdio: inherit` as a flag to the `spawn` command to get the exact same output. _This will also add the ANSI colours included in the Theme Kit output, which is a nice touch as well._

**I think the above alternative should be implemented at some point (more faithful output to the Theme Kit binary), but only when the underlying issue with Theme Kit is resolved.**

**Closed** 2018-09-21 13:43 UTC
